name: Algolia push records

on: [push]

jobs:
  build:
    name: Algolia push records

    runs-on: ubuntu-latest

    steps:
      - name: Set Node.js 20.x
        uses: actions/setup-node@master
        with:
          node-version: 20.x
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: '3.3'
      - name: Install dependencies and push records
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec jekyll algolia
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}